### ISSUE TITLE
SSL Certificate is invalid error, job status is Success

### ISSUE THREAD

**Issue by CptLolliPants** [orangeglasses/vROAST#15]
A new job gives errors about an SSL certificate, but still returns that the job is succesfull. 

```+150msFailure during jobexecution
+152msError! the SSL certificate is invalid
+162msStacktrace:    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at MedKit.SourceControl.GitScc.pullGitChangesToLocal() in /app/Common/Sourcecontrol/SourceControl.cs:line 117
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 63
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 41

**Comment by floreseken** [comment]
Are you using a git server with a self signed certificate?

**Comment by CptLolliPants** [comment]
No, gitlab server has a signed certificate from Digicert.

**Comment by floreseken** [comment]
Hmm okay.. but somehow not trusted by LibGit2Sharp apparently, Do you think we should ignore certificate errors?

**Comment by floreseken** [comment]
btw we already ignore vRO cert errors.

**Comment by floreseken** [comment]
In 0.7.6 the job will have a failed status if an error occurs.

**Comment by CptLolliPants** [comment]
If the certificate is set, I find it quite strange to get a SSL Certificate failure? Ignoring it would not be a problem I guess.

**Comment by floreseken** [comment]
Invalid Git certs are now ignored in 0.7.6, and failing jobs listed as failed in the portal.
Closing this issue.
