### ISSUE TITLE
unable to push vRO content due to parsing error

### ISSUE THREAD

**Issue by hackathon0317** [orangeglasses/vROAST#20]
Unable to sync content due to parsing error. This occurs right out of the gate on the first job

```
+15msStart job execution
+17msStarting with myfirstpush [pushtovro]
+19mspluginRepoPath: /tmp/vroast/pluginRepo
+21msWorking src path: /tmp/vroast/work/srcCache/https:--xxxxx.xxxxx.net-xxxx-xxxx-xxxx.git/master/pushtovro
+23msThis is a pull from GIT and push to vRO job. Using host: xxxx.xxxx.xxxx.net:443
+25msSetting up sourcecontrol. Pulling remote: https://xxxx.xxxx.net/xxxx/xxxx/vroastpoc.git to /tmp/vroast/work/srcCache/https:--xxxx.xxxx.net-xxxx-xxxx-vroastpoc.git/master/pushtovro
+27msLocal working folder path: /tmp/vroast/work/srcCache/https:--xxxx.xxxx.net-xxxx-xxxx-xxxx.git/master/pushtovro. Pulling git repo.
+8.192sDone pulling repo. Checking contents..
+8.196sLast commit of the repo is 9457cd5acb51a9ddd1e142ad67fe99db635628b2
+8.198sLast synced commit to vRO is 
+8.211sNow cleaning xml path: /tmp/vroast/work/vroCache/xxxx.xxxx.xxxx.net/pushtovro/action
+8.284sDone pulling GIT content. Now converting stuff..
+8.294sTS - > Actions (xml)
+10.120sXML - > Action file (.zip)
+10.401sNow pushing vRO content..
+10.526sFailure during jobexecution
+10.530sError! Unexpected character encountered while parsing value: . Path '', line 0, position 0.
+10.532sStacktrace:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at MedKit.vRO.vROClient.getAllCategories(WebClient web, String type, Boolean isRoot) in /app/Common/vRO/vROClient.cs:line 595
   at MedKit.vRO.vROClient.getExistingCategories(WebClient web, String type, Boolean isRoot) in /app/Common/vRO/vROClient.cs:line 575
   at MedKit.vRO.vROClient.PutContent(String type, List`1 onlyIncludeFiles) in /app/Common/vRO/vROClient.cs:line 343
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 136
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 53
```

**Comment by getstek** [comment]
Did you ever get a solution to this?
