### ISSUE TITLE
Failure while getting vro-content: Unable to download definition file

### ISSUE THREAD

**Issue by vkNIL** [orangeglasses/vROAST#33]
With vRO 7.5 it fails while retrieving content from vro. The error log: 

`+3.477s    Now getting vRO content..`
`+3.809s Failure during jobexecution`
`+3.812s Error! Unable to download defintion file: TeamFoundationServer version: 7.5.0-SNAPSHOT. Make sure the plugin with this version exists on vroapi.com and that the engine can access it`
`+3.820s Stacktrace:    at MedKit.vRO.vROClient.ProcessPlugin(ApiPlugin p) in /app/Common/vRO/vROClient.cs:line 304
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MedKit.vRO.vROClient.GetContent(String type) in /app/Common/vRO/vROClient.cs:line 143
   at MedKit.vRO.vROClient.GetAllContent() in /app/Common/vRO/vROClient.cs:line 208
   at MedKit.Jobs.JobExecuter.executePullFromVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 186
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 100
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 53`

**Comment by wasbert** [comment]
I have the same error, Error! Unable to download defintion file: DynamicTypes version: 1.3.1. Make sure the plugin with this version exists on vroapi.com and that the engine can access it. My vRoast appliance is behind a firewall and has no access to vroapi.com, I requested a rule to connect to enable trafic from the Appliance to www.vroapi.com. When the rule is inplace I will let you know if this fixed my problem. I did see a issue where offline availability of the vroapi data is requested hopefully this will soon be available.
