### ISSUE TITLE
Unable to import content from vRO 7.4 and 7.5

### ISSUE THREAD

**Issue by ivgivanov** [orangeglasses/vROAST#9]
Hello,
When trying to run the pushtovRO job against vRO 7.4 I'm getting the following error:
```
+7.156sFailure during jobexecution
+7.159sError! Unable to download defintion file: VCO version: 7.4.0. Make sure the plugin with this version exists on vroapi.com and that the engine can access it
+7.167sStacktrace:    at MedKit.vRO.vROClient.ProcessPlugin(ApiPlugin p) in /app/Common/vRO/vROClient.cs:line 286
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MedKit.vRO.vROClient.GetContent(String type) in /app/Common/vRO/vROClient.cs:line 132
   at MedKit.vRO.vROClient.GetAllContent() in /app/Common/vRO/vROClient.cs:line 190
   at MedKit.Jobs.JobExecuter.executePullFromVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 166
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 81
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 41
```

Here is the result when pointed to vRO 7.5:
```
+3.718sFailure during jobexecution
+3.721sError! Unable to download defintion file: DynamicTypes version: 1.3.1. Make sure the plugin with this version exists on vroapi.com and that the engine can access it
+3.729sStacktrace:    at MedKit.vRO.vROClient.ProcessPlugin(ApiPlugin p) in /app/Common/vRO/vROClient.cs:line 286
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MedKit.vRO.vROClient.GetContent(String type) in /app/Common/vRO/vROClient.cs:line 132
   at MedKit.vRO.vROClient.GetAllContent() in /app/Common/vRO/vROClient.cs:line 190
   at MedKit.Jobs.JobExecuter.executePullFromVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 166
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 81
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 41
```

It works with vRO 7.3

Can you please add the new versions of the inbox plugins to vroapi.com? 
Thanks!

**Comment by floreseken** [comment]
Yes, no problem. If you could provide us with the plugin files somehow.. Are they small enough to be emailed?

**Comment by ivgivanov** [comment]
Hello,
I just sent you an email. Let me know if you have issues accessing them.

**Comment by ruurdk** [comment]
Included in vroapi

**Comment by floreseken** [comment]
I'll go ahead and close this issue, since it is resolved.
